spring:
application:
name: Config-Default
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    logging:
      level:
        com.netflix.eureka: OFF
        com.netflix.discovery: OFF
    service-url:
      defaultZone: http://localhost:8761/eureka/
